Reorganize GH action workflows

diff --git a/.github/workflows/cd-config.yml b/.github/workflows/cd-config.yml
--- a/.github/workflows/cd-config.yml
+++ b/.github/workflows/cd-config.yml
@@ -2,14 +2,23 @@ name: GitHub CD
 
 on:
   push:
+    branches:
+      - master
     tags:
       - trellis-[0-9]+.[0-9]+.[0-9]+
 
 jobs:
-  build:
+  validation:
+    name: Gradle Validation
     runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2.1.0
+      - uses: gradle/wrapper-validation-action@v1.0.3
 
+  build:
     name: Java 11 environment
+    runs-on: ubuntu-latest
+    needs: [validation]
 
     services:
       postgres:
@@ -38,11 +47,46 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-  dockerhub:
+  security:
+    name: Security analysis
     needs: [build]
     runs-on: ubuntu-latest
 
-    name: Deploy docker container to DockerHub
+    steps:
+    - uses: actions/checkout@v2.1.0
+    - name: Run Snyk to check for vulnerabilities
+      env:
+        PROJECT_PATH: /project/trellis
+        SNYK_ORG: ${{ secrets.SNYK_ORG }}
+        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      # Only run security scans if integration is set up
+      run: |
+          if [ "$SNYK_ORG" != "" ]; then
+            # don't fail the build if snyk doesn't complete successfully
+            docker run --name snyk -e SNYK_TOKEN -e PROJECT_PATH -v "/home/runner/work/trellis":"/project" snyk/snyk-cli:gradle-5.4 "monitor --all-sub-projects --org=$SNYK_ORG" || true
+          fi
+
+  sonatype:
+    name: Deploy artifacts to Sonatype
+    needs: [build]
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2.1.0
+    - name: Set up JDK 8
+      uses: actions/setup-java@v1.3.0
+      with:
+        java-version: 8
+    - name: Publish to Sonatype
+      run: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew publish ; fi
+      env:
+          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
+          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
+
+  dockerhub:
+    name: Deploy Docker containers to DockerHub
+    needs: [build]
+    runs-on: ubuntu-latest
+
     steps:
     - uses: actions/checkout@v2.1.0
     - name: Set up JDK 11
@@ -50,7 +94,7 @@ jobs:
       with:
         java-version: 11
 
-    - name: Publish Docker Container
+    - name: Publish Docker Containers
       run: |
         echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
         ./buildtools/src/main/resources/docker/publishToDockerHub.sh
@@ -59,7 +103,7 @@ jobs:
     needs: [build]
     runs-on: ubuntu-latest
 
-    name: Deploy docker container to GitHub
+    name: Deploy Docker containers to GitHub
     steps:
     - uses: actions/checkout@v2.1.0
     - name: Set up JDK 11
@@ -67,7 +111,7 @@ jobs:
       with:
         java-version: 11
 
-    - name: Publish Docker Container
+    - name: Publish Docker Containers
       run: |
         echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
         ./buildtools/src/main/resources/docker/publishToGitHub.sh
